# -*- coding: utf-8 -*-
"""Email Automation Using NLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xu43aEKaNd2T9-Zm-hkAEl71CUvAZeUZ
"""

!Pip install transformers
!pip install datasets
!pip install sentencepiece
!pip install accelerate
!pip install evaluate

import pandas as pd
import numpy as np

from transformers import(
    AutoTokenizer,
    AutoModelForSeq2SeqLM,

)

import torch

data = {
    "instruction":[
        "promotion request",
        "leave request",
        "complaint",
        "follow up"
    ],

    "email":[
        "Dear Manager...",
        "Dear Sir...",
        "Dear Customer Support...",
        "Dear Recruiter..."
    ]
}

df = pd.DataFrame(data)
df.head()

import re

def clean_text(text):

  text = text.lower()

  text = text.lower()

  text =resub(
      r'[^a-zA-Z ]',
      '',
      text
  )

  return text

import nltk

nltk.download('stopwords')

from nltk.corpus import stopwords

stop_words = stopwords.words('english')

print(stop_words[:20])

from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

print(
    stemmer.stem("running")
)

import nltk
nltk.download('wordnet')

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

print(
    lemmatizer.lemmatize("running")
)

{
    "instruction":
    "write follow up email",
    "response":
    "Dear Recruiter..."
}

from datasets import Dataset

dataset = Dataset.from_pandas(df)

dataset

MODEL_NAME = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def preprocess(example):

  model_inputs = tokenizer(
      example["instruction"],
      truncation=True,
      padding="max_length",
      max_length=128
  )

  labels = tokenizer(
      example["email"],
      truncation=True,
      padding="max_length",
      max_length=512,
  )

  model_inputs['labels'] = labels['input_ids']

  return model_inputs

tokenized_dataset = dataset.map(
    preprocess
)

from transformers import (
    TrainingArguments,
    Trainer,
)

training_args = TrainingArguments(
    output_dir="./email_models",

    num_train_epochs=3,

    logging_steps=10,

    save_steps=50
)

model = AutoModelForSeq2SeqLM.from_pretrained(
    MODEL_NAME
)

print("model Loaded Successfully")



trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset
)

trainer.train()

trainer.save_model(
    "email_writer_model"
 )

model = AutoModelForSeq2SeqLM.from_pretrained(
    "email_writer_model"
)

