# -*- coding: utf-8 -*-
"""generative ai logo generative using Latent Diffision model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c8Yw4auVhJ9K1Qx3epPzZ5We1OtIS3ZG
"""

pip install diffusers transformers accelerate safetensors torch torchvision pillow matplotlib -q

import torch

from diffusers import StableDiffusionPipeline

import matplotlib.pyplot as plt

print("CUDA Available:", torch.cuda.is_available())

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
     model_id
)

pipe =pipe.to('cpu')

pipe.enable_attention_slicing()

prompt = """
minimalist AI startup logo,
mordern vector logo,
clean typography,
blue and white colour palette,
professional branding,
flat design,
high quality logo
"""

negative_prompt ="""
blurry,
low quality,
distorted text,
extra shapes,
watermark,
complex background"""

image = pipe(
    prompt=prompt,
    negative_prompt=negative_prompt,
    num_inference_steps=20,
    guidance_scale=7,
    height=384,
    width=384
).images[0]

image

